use_frameworks!

target 'hexagonmatch-pods_Example' do
  pod 'hexagonmatch-pods', :path => '../'

  target 'hexagonmatch-pods_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
